[build]
target = "../x86_64-unknown-litchi-user.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-litchi-user]
rustflags = [
    "-Clink-arg=--image-base=0x111100000000", "-Clink-arg=--entry=_user_main"
]
