cargo-features = ["strip"]

[workspace]
members = [
    "litchi-boot",
    "litchi-common",
    "litchi-kernel",
    "litchi-user",
    "litchi-user-common",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
strip = true
