[package]
name = "litchi-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
size_format = "1.0"
uefi = "0.15"
log = "0.4"
x86_64 = "0.14"
