[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
    "-Clink-arg=--image-base=0xdead00000000"
]
